# CLASE TIQUETE
# AUTORES: JHONEYKER DELGADO, EMMANUEL VALENCIA, SIMON GUARIN, CAMILO MIRANDA Y JACOBO LEAL.
from gestorAplicacion.hangar import *
from gestorAplicacion.adminVuelos.Tiquete import Tiquete

# CONTIENE LA INFORMACION PERTINENTE DE UN VUELO, ADEMAS DE LA LISTA DE TIQUETES QUE FUERON ASOCIADOS AL MISMO.
class Vuelo():

    # ATRIBUTOS
